### ISSUE TITLE
DW Approved with Notes

### ISSUE THREAD

**Issue by jonalf** [KennethChin0/finalProject#1]
The idea is approved, but your implementation design needs more thought. If this is supposed to be a networked game, why would signals, semaphores and shared memory be needed? These things are only useful if two programs are running and communicating with each other. Please update your design after thinking about this more and respond to this issue when you have done so.

**Comment by jonalf** [comment]
this issue is still open

**Comment by derek-lao** [comment]
Updated!

**Comment by jonalf** [comment]
approved

make it so
